#!/usr/bin/env python3
"""Regenerate pricing.json — the per-token rate table the bridge bills against.

Rates are pulled from LiteLLM's model_prices_and_context_window.json, which
tracks both Anthropic and OpenAI pricing and carries the four fields a turn's
cost needs: uncached input, output, cache read, and cache write.

The bridge never fetches at runtime — it is a deterministic local pipe and has
to work offline — so this script is the seam: run it when a model lands or a
price changes, eyeball the diff, commit the result.

    scripts/refresh-pricing.py            # rewrite pricing.json
    scripts/refresh-pricing.py --check    # exit 1 if stale (for CI)

Adding a model: put its id in MODELS. The id must be what the engine reports
at turn end — the `model` field of a Claude transcript's assistant entries, or
the `model` field of Codex's Stop-hook payload — because that string is what
the bridge looks up.
"""
import argparse
import json
import os
import sys
import urllib.request

SOURCE = (
    "https://raw.githubusercontent.com/BerriAI/litellm/main/"
    "model_prices_and_context_window.json"
)

# Models a worker can actually run. Anything absent at runtime bills at
# FALLBACK rates and is logged, so an unknown model costs money rather than
# silently costing nothing.
MODELS = [
    # Claude Code
    "claude-opus-5",
    "claude-fable-5",
    "claude-opus-4-8",
    "claude-opus-4-7",
    "claude-opus-4-6",
    "claude-sonnet-5",
    "claude-sonnet-4-6",
    "claude-haiku-4-5",
    # Codex
    "gpt-5.6",
    "gpt-5.6-sol",
    "gpt-5.6-terra",
    "gpt-5.6-luna",
    "gpt-5.5",
]

# Rates are per token, not per million — that is the unit the source uses and
# the unit the bridge multiplies by, so no scaling happens anywhere.
FIELDS = {
    "input": "input_cost_per_token",
    "output": "output_cost_per_token",
    "cache_read": "cache_read_input_token_cost",
    "cache_write": "cache_creation_input_token_cost",
}

OUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.realpath(__file__))), "pricing.json"
)


def build():
    with urllib.request.urlopen(SOURCE, timeout=60) as r:
        source = json.load(r)

    models, missing = {}, []
    for name in MODELS:
        entry = source.get(name)
        if not isinstance(entry, dict):
            missing.append(name)
            continue
        rates = {}
        for key, field in FIELDS.items():
            value = entry.get(field)
            if isinstance(value, (int, float)):
                rates[key] = float(value)
        # An entry with no input/output rate is useless; treat it as missing
        # rather than writing a half-populated row the bridge would trust.
        if "input" not in rates or "output" not in rates:
            missing.append(name)
            continue
        # Cache rates are optional upstream. Fall back to the documented
        # Anthropic multipliers (read 0.1x, write 1.25x), which OpenAI's
        # cached-input discount also approximates.
        rates.setdefault("cache_read", round(rates["input"] * 0.1, 12))
        rates.setdefault("cache_write", round(rates["input"] * 1.25, 12))
        models[name] = rates

    return {
        "_source": SOURCE,
        # Both providers price their fast/priority tier at exactly 2x standard
        # per-token rates, so one multiplier covers the fleet:
        #   OpenAI  — "Fast mode" (service_tier priority/fast, renamed from
        #             Priority processing on 2026-07-30): 2x standard.
        #   Anthropic — fast mode on Opus 5: $10/$50 vs $5/$25 standard.
        # Revisit if either ever diverges from 2x.
        "fast_multiplier": 2.0,
        "_note": (
            "Generated by scripts/refresh-pricing.py — do not hand-edit. "
            "Rates are USD per token. Workers run on subscriptions, so these "
            "are a cost-weighting for comparing spend across engines, not a "
            "bill."
        ),
        "fallback": {
            "input": 5e-06,
            "output": 2.5e-05,
            "cache_read": 5e-07,
            "cache_write": 6.25e-06,
        },
        "models": models,
    }, missing


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if pricing.json differs from the source")
    args = ap.parse_args()

    fresh, missing = build()
    for name in missing:
        print(f"warning: no usable rates upstream for {name}", file=sys.stderr)

    rendered = json.dumps(fresh, indent=2, sort_keys=True) + "\n"

    if args.check:
        try:
            with open(OUT) as f:
                current = f.read()
        except FileNotFoundError:
            print("pricing.json is missing", file=sys.stderr)
            return 1
        if current != rendered:
            print("pricing.json is stale — run scripts/refresh-pricing.py",
                  file=sys.stderr)
            return 1
        print("pricing.json is current")
        return 0

    with open(OUT, "w") as f:
        f.write(rendered)
    print(f"wrote {OUT} ({len(fresh['models'])} models)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
